name: hls4ml-pynq-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyterhub
  - pydot
  - graphviz
  - pip
  - pip:
    - jupyter
    - tensorflow==2.3.1
    - tensorflow_datasets
    - git+https://github.com/nicologhielmetti/hls4ml@pynq-pr#egg=hls4ml[profiling]
    - git+https://github.com/google/qkeras.git#egg=qkeras
    - scikit-learn
    - brainflow
    - asyncio
    - websockets
    
