// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module shift_line_buffer_array_ap_fixed_10u_config10_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        kernel_window_80_V_write,
        kernel_window_81_V_write,
        kernel_window_82_V_write,
        kernel_window_83_V_write,
        kernel_window_84_V_write,
        kernel_window_85_V_write,
        kernel_window_86_V_write,
        kernel_window_87_V_write,
        kernel_window_88_V_write,
        kernel_window_89_V_write,
        kernel_window_10_V_read,
        kernel_window_11_V_read,
        kernel_window_12_V_read,
        kernel_window_13_V_read,
        kernel_window_14_V_read,
        kernel_window_15_V_read,
        kernel_window_16_V_read,
        kernel_window_17_V_read,
        kernel_window_18_V_read,
        kernel_window_19_V_read,
        kernel_window_20_V_read,
        kernel_window_21_V_read,
        kernel_window_22_V_read,
        kernel_window_23_V_read,
        kernel_window_24_V_read,
        kernel_window_25_V_read,
        kernel_window_26_V_read,
        kernel_window_27_V_read,
        kernel_window_28_V_read,
        kernel_window_29_V_read,
        kernel_window_40_V_read,
        kernel_window_41_V_read,
        kernel_window_42_V_read,
        kernel_window_43_V_read,
        kernel_window_44_V_read,
        kernel_window_45_V_read,
        kernel_window_46_V_read,
        kernel_window_47_V_read,
        kernel_window_48_V_read,
        kernel_window_49_V_read,
        kernel_window_50_V_read,
        kernel_window_51_V_read,
        kernel_window_52_V_read,
        kernel_window_53_V_read,
        kernel_window_54_V_read,
        kernel_window_55_V_read,
        kernel_window_56_V_read,
        kernel_window_57_V_read,
        kernel_window_58_V_read,
        kernel_window_59_V_read,
        kernel_window_70_V_read,
        kernel_window_71_V_read,
        kernel_window_72_V_read,
        kernel_window_73_V_read,
        kernel_window_74_V_read,
        kernel_window_75_V_read,
        kernel_window_76_V_read,
        kernel_window_77_V_read,
        kernel_window_78_V_read,
        kernel_window_79_V_read,
        kernel_window_80_V_read,
        kernel_window_81_V_read,
        kernel_window_82_V_read,
        kernel_window_83_V_read,
        kernel_window_84_V_read,
        kernel_window_85_V_read,
        kernel_window_86_V_read,
        kernel_window_87_V_read,
        kernel_window_88_V_read,
        kernel_window_89_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31,
        ap_return_32,
        ap_return_33,
        ap_return_34,
        ap_return_35,
        ap_return_36,
        ap_return_37,
        ap_return_38,
        ap_return_39,
        ap_return_40,
        ap_return_41,
        ap_return_42,
        ap_return_43,
        ap_return_44,
        ap_return_45,
        ap_return_46,
        ap_return_47,
        ap_return_48,
        ap_return_49,
        ap_return_50,
        ap_return_51,
        ap_return_52,
        ap_return_53,
        ap_return_54,
        ap_return_55,
        ap_return_56,
        ap_return_57,
        ap_return_58,
        ap_return_59,
        ap_return_60,
        ap_return_61,
        ap_return_62,
        ap_return_63,
        ap_return_64,
        ap_return_65,
        ap_return_66,
        ap_return_67,
        ap_return_68,
        ap_return_69,
        ap_return_70,
        ap_return_71,
        ap_return_72,
        ap_return_73,
        ap_return_74,
        ap_return_75,
        ap_return_76,
        ap_return_77,
        ap_return_78,
        ap_return_79,
        ap_return_80,
        ap_return_81,
        ap_return_82,
        ap_return_83,
        ap_return_84,
        ap_return_85,
        ap_return_86,
        ap_return_87,
        ap_return_88,
        ap_return_89
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] kernel_window_80_V_write;
input  [15:0] kernel_window_81_V_write;
input  [15:0] kernel_window_82_V_write;
input  [15:0] kernel_window_83_V_write;
input  [15:0] kernel_window_84_V_write;
input  [15:0] kernel_window_85_V_write;
input  [15:0] kernel_window_86_V_write;
input  [15:0] kernel_window_87_V_write;
input  [15:0] kernel_window_88_V_write;
input  [15:0] kernel_window_89_V_write;
input  [15:0] kernel_window_10_V_read;
input  [15:0] kernel_window_11_V_read;
input  [15:0] kernel_window_12_V_read;
input  [15:0] kernel_window_13_V_read;
input  [15:0] kernel_window_14_V_read;
input  [15:0] kernel_window_15_V_read;
input  [15:0] kernel_window_16_V_read;
input  [15:0] kernel_window_17_V_read;
input  [15:0] kernel_window_18_V_read;
input  [15:0] kernel_window_19_V_read;
input  [15:0] kernel_window_20_V_read;
input  [15:0] kernel_window_21_V_read;
input  [15:0] kernel_window_22_V_read;
input  [15:0] kernel_window_23_V_read;
input  [15:0] kernel_window_24_V_read;
input  [15:0] kernel_window_25_V_read;
input  [15:0] kernel_window_26_V_read;
input  [15:0] kernel_window_27_V_read;
input  [15:0] kernel_window_28_V_read;
input  [15:0] kernel_window_29_V_read;
input  [15:0] kernel_window_40_V_read;
input  [15:0] kernel_window_41_V_read;
input  [15:0] kernel_window_42_V_read;
input  [15:0] kernel_window_43_V_read;
input  [15:0] kernel_window_44_V_read;
input  [15:0] kernel_window_45_V_read;
input  [15:0] kernel_window_46_V_read;
input  [15:0] kernel_window_47_V_read;
input  [15:0] kernel_window_48_V_read;
input  [15:0] kernel_window_49_V_read;
input  [15:0] kernel_window_50_V_read;
input  [15:0] kernel_window_51_V_read;
input  [15:0] kernel_window_52_V_read;
input  [15:0] kernel_window_53_V_read;
input  [15:0] kernel_window_54_V_read;
input  [15:0] kernel_window_55_V_read;
input  [15:0] kernel_window_56_V_read;
input  [15:0] kernel_window_57_V_read;
input  [15:0] kernel_window_58_V_read;
input  [15:0] kernel_window_59_V_read;
input  [15:0] kernel_window_70_V_read;
input  [15:0] kernel_window_71_V_read;
input  [15:0] kernel_window_72_V_read;
input  [15:0] kernel_window_73_V_read;
input  [15:0] kernel_window_74_V_read;
input  [15:0] kernel_window_75_V_read;
input  [15:0] kernel_window_76_V_read;
input  [15:0] kernel_window_77_V_read;
input  [15:0] kernel_window_78_V_read;
input  [15:0] kernel_window_79_V_read;
input  [15:0] kernel_window_80_V_read;
input  [15:0] kernel_window_81_V_read;
input  [15:0] kernel_window_82_V_read;
input  [15:0] kernel_window_83_V_read;
input  [15:0] kernel_window_84_V_read;
input  [15:0] kernel_window_85_V_read;
input  [15:0] kernel_window_86_V_read;
input  [15:0] kernel_window_87_V_read;
input  [15:0] kernel_window_88_V_read;
input  [15:0] kernel_window_89_V_read;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;
output  [15:0] ap_return_14;
output  [15:0] ap_return_15;
output  [15:0] ap_return_16;
output  [15:0] ap_return_17;
output  [15:0] ap_return_18;
output  [15:0] ap_return_19;
output  [15:0] ap_return_20;
output  [15:0] ap_return_21;
output  [15:0] ap_return_22;
output  [15:0] ap_return_23;
output  [15:0] ap_return_24;
output  [15:0] ap_return_25;
output  [15:0] ap_return_26;
output  [15:0] ap_return_27;
output  [15:0] ap_return_28;
output  [15:0] ap_return_29;
output  [15:0] ap_return_30;
output  [15:0] ap_return_31;
output  [15:0] ap_return_32;
output  [15:0] ap_return_33;
output  [15:0] ap_return_34;
output  [15:0] ap_return_35;
output  [15:0] ap_return_36;
output  [15:0] ap_return_37;
output  [15:0] ap_return_38;
output  [15:0] ap_return_39;
output  [15:0] ap_return_40;
output  [15:0] ap_return_41;
output  [15:0] ap_return_42;
output  [15:0] ap_return_43;
output  [15:0] ap_return_44;
output  [15:0] ap_return_45;
output  [15:0] ap_return_46;
output  [15:0] ap_return_47;
output  [15:0] ap_return_48;
output  [15:0] ap_return_49;
output  [15:0] ap_return_50;
output  [15:0] ap_return_51;
output  [15:0] ap_return_52;
output  [15:0] ap_return_53;
output  [15:0] ap_return_54;
output  [15:0] ap_return_55;
output  [15:0] ap_return_56;
output  [15:0] ap_return_57;
output  [15:0] ap_return_58;
output  [15:0] ap_return_59;
output  [15:0] ap_return_60;
output  [15:0] ap_return_61;
output  [15:0] ap_return_62;
output  [15:0] ap_return_63;
output  [15:0] ap_return_64;
output  [15:0] ap_return_65;
output  [15:0] ap_return_66;
output  [15:0] ap_return_67;
output  [15:0] ap_return_68;
output  [15:0] ap_return_69;
output  [15:0] ap_return_70;
output  [15:0] ap_return_71;
output  [15:0] ap_return_72;
output  [15:0] ap_return_73;
output  [15:0] ap_return_74;
output  [15:0] ap_return_75;
output  [15:0] ap_return_76;
output  [15:0] ap_return_77;
output  [15:0] ap_return_78;
output  [15:0] ap_return_79;
output  [15:0] ap_return_80;
output  [15:0] ap_return_81;
output  [15:0] ap_return_82;
output  [15:0] ap_return_83;
output  [15:0] ap_return_84;
output  [15:0] ap_return_85;
output  [15:0] ap_return_86;
output  [15:0] ap_return_87;
output  [15:0] ap_return_88;
output  [15:0] ap_return_89;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    line_buffer_Array_V_0_0_ce0;
reg    line_buffer_Array_V_0_0_we0;
wire   [15:0] line_buffer_Array_V_0_0_q0;
reg    line_buffer_Array_V_1581_0_ce0;
reg    line_buffer_Array_V_1581_0_we0;
wire   [15:0] line_buffer_Array_V_1581_0_q0;
reg    line_buffer_Array_V_0_1_ce0;
reg    line_buffer_Array_V_0_1_we0;
wire   [15:0] line_buffer_Array_V_0_1_q0;
reg    line_buffer_Array_V_1581_1_ce0;
reg    line_buffer_Array_V_1581_1_we0;
wire   [15:0] line_buffer_Array_V_1581_1_q0;
reg    line_buffer_Array_V_0_2_ce0;
reg    line_buffer_Array_V_0_2_we0;
wire   [15:0] line_buffer_Array_V_0_2_q0;
reg    line_buffer_Array_V_1581_2_ce0;
reg    line_buffer_Array_V_1581_2_we0;
wire   [15:0] line_buffer_Array_V_1581_2_q0;
reg    line_buffer_Array_V_0_3_ce0;
reg    line_buffer_Array_V_0_3_we0;
wire   [15:0] line_buffer_Array_V_0_3_q0;
reg    line_buffer_Array_V_1581_3_ce0;
reg    line_buffer_Array_V_1581_3_we0;
wire   [15:0] line_buffer_Array_V_1581_3_q0;
reg    line_buffer_Array_V_0_4_ce0;
reg    line_buffer_Array_V_0_4_we0;
wire   [15:0] line_buffer_Array_V_0_4_q0;
reg    line_buffer_Array_V_1581_4_ce0;
reg    line_buffer_Array_V_1581_4_we0;
wire   [15:0] line_buffer_Array_V_1581_4_q0;
reg    line_buffer_Array_V_0_5_ce0;
reg    line_buffer_Array_V_0_5_we0;
wire   [15:0] line_buffer_Array_V_0_5_q0;
reg    line_buffer_Array_V_1581_5_ce0;
reg    line_buffer_Array_V_1581_5_we0;
wire   [15:0] line_buffer_Array_V_1581_5_q0;
reg    line_buffer_Array_V_0_6_ce0;
reg    line_buffer_Array_V_0_6_we0;
wire   [15:0] line_buffer_Array_V_0_6_q0;
reg    line_buffer_Array_V_1581_6_ce0;
reg    line_buffer_Array_V_1581_6_we0;
wire   [15:0] line_buffer_Array_V_1581_6_q0;
reg    line_buffer_Array_V_0_7_ce0;
reg    line_buffer_Array_V_0_7_we0;
wire   [15:0] line_buffer_Array_V_0_7_q0;
reg    line_buffer_Array_V_1581_7_ce0;
reg    line_buffer_Array_V_1581_7_we0;
wire   [15:0] line_buffer_Array_V_1581_7_q0;
reg    line_buffer_Array_V_0_8_ce0;
reg    line_buffer_Array_V_0_8_we0;
wire   [15:0] line_buffer_Array_V_0_8_q0;
reg    line_buffer_Array_V_1581_8_ce0;
reg    line_buffer_Array_V_1581_8_we0;
wire   [15:0] line_buffer_Array_V_1581_8_q0;
reg    line_buffer_Array_V_0_9_ce0;
reg    line_buffer_Array_V_0_9_we0;
wire   [15:0] line_buffer_Array_V_0_9_q0;
reg    line_buffer_Array_V_1581_9_ce0;
reg    line_buffer_Array_V_1581_9_we0;
wire   [15:0] line_buffer_Array_V_1581_9_q0;
reg   [0:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
end

shift_line_buffer_array_ap_fixed_10u_config10_s_line_buffLf8 #(
    .DataWidth( 16 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
line_buffer_Array_V_0_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd5),
    .ce0(line_buffer_Array_V_0_0_ce0),
    .we0(line_buffer_Array_V_0_0_we0),
    .d0(kernel_window_80_V_write),
    .q0(line_buffer_Array_V_0_0_q0)
);

shift_line_buffer_array_ap_fixed_10u_config10_s_line_buffLf8 #(
    .DataWidth( 16 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
line_buffer_Array_V_1581_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd5),
    .ce0(line_buffer_Array_V_1581_0_ce0),
    .we0(line_buffer_Array_V_1581_0_we0),
    .d0(line_buffer_Array_V_0_0_q0),
    .q0(line_buffer_Array_V_1581_0_q0)
);

shift_line_buffer_array_ap_fixed_10u_config10_s_line_buffLf8 #(
    .DataWidth( 16 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
line_buffer_Array_V_0_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd5),
    .ce0(line_buffer_Array_V_0_1_ce0),
    .we0(line_buffer_Array_V_0_1_we0),
    .d0(kernel_window_81_V_write),
    .q0(line_buffer_Array_V_0_1_q0)
);

shift_line_buffer_array_ap_fixed_10u_config10_s_line_buffLf8 #(
    .DataWidth( 16 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
line_buffer_Array_V_1581_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd5),
    .ce0(line_buffer_Array_V_1581_1_ce0),
    .we0(line_buffer_Array_V_1581_1_we0),
    .d0(line_buffer_Array_V_0_1_q0),
    .q0(line_buffer_Array_V_1581_1_q0)
);

shift_line_buffer_array_ap_fixed_10u_config10_s_line_buffLf8 #(
    .DataWidth( 16 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
line_buffer_Array_V_0_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd5),
    .ce0(line_buffer_Array_V_0_2_ce0),
    .we0(line_buffer_Array_V_0_2_we0),
    .d0(kernel_window_82_V_write),
    .q0(line_buffer_Array_V_0_2_q0)
);

shift_line_buffer_array_ap_fixed_10u_config10_s_line_buffLf8 #(
    .DataWidth( 16 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
line_buffer_Array_V_1581_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd5),
    .ce0(line_buffer_Array_V_1581_2_ce0),
    .we0(line_buffer_Array_V_1581_2_we0),
    .d0(line_buffer_Array_V_0_2_q0),
    .q0(line_buffer_Array_V_1581_2_q0)
);

shift_line_buffer_array_ap_fixed_10u_config10_s_line_buffLf8 #(
    .DataWidth( 16 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
line_buffer_Array_V_0_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd5),
    .ce0(line_buffer_Array_V_0_3_ce0),
    .we0(line_buffer_Array_V_0_3_we0),
    .d0(kernel_window_83_V_write),
    .q0(line_buffer_Array_V_0_3_q0)
);

shift_line_buffer_array_ap_fixed_10u_config10_s_line_buffLf8 #(
    .DataWidth( 16 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
line_buffer_Array_V_1581_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd5),
    .ce0(line_buffer_Array_V_1581_3_ce0),
    .we0(line_buffer_Array_V_1581_3_we0),
    .d0(line_buffer_Array_V_0_3_q0),
    .q0(line_buffer_Array_V_1581_3_q0)
);

shift_line_buffer_array_ap_fixed_10u_config10_s_line_buffLf8 #(
    .DataWidth( 16 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
line_buffer_Array_V_0_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd5),
    .ce0(line_buffer_Array_V_0_4_ce0),
    .we0(line_buffer_Array_V_0_4_we0),
    .d0(kernel_window_84_V_write),
    .q0(line_buffer_Array_V_0_4_q0)
);

shift_line_buffer_array_ap_fixed_10u_config10_s_line_buffLf8 #(
    .DataWidth( 16 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
line_buffer_Array_V_1581_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd5),
    .ce0(line_buffer_Array_V_1581_4_ce0),
    .we0(line_buffer_Array_V_1581_4_we0),
    .d0(line_buffer_Array_V_0_4_q0),
    .q0(line_buffer_Array_V_1581_4_q0)
);

shift_line_buffer_array_ap_fixed_10u_config10_s_line_buffLf8 #(
    .DataWidth( 16 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
line_buffer_Array_V_0_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd5),
    .ce0(line_buffer_Array_V_0_5_ce0),
    .we0(line_buffer_Array_V_0_5_we0),
    .d0(kernel_window_85_V_write),
    .q0(line_buffer_Array_V_0_5_q0)
);

shift_line_buffer_array_ap_fixed_10u_config10_s_line_buffLf8 #(
    .DataWidth( 16 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
line_buffer_Array_V_1581_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd5),
    .ce0(line_buffer_Array_V_1581_5_ce0),
    .we0(line_buffer_Array_V_1581_5_we0),
    .d0(line_buffer_Array_V_0_5_q0),
    .q0(line_buffer_Array_V_1581_5_q0)
);

shift_line_buffer_array_ap_fixed_10u_config10_s_line_buffLf8 #(
    .DataWidth( 16 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
line_buffer_Array_V_0_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd5),
    .ce0(line_buffer_Array_V_0_6_ce0),
    .we0(line_buffer_Array_V_0_6_we0),
    .d0(kernel_window_86_V_write),
    .q0(line_buffer_Array_V_0_6_q0)
);

shift_line_buffer_array_ap_fixed_10u_config10_s_line_buffLf8 #(
    .DataWidth( 16 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
line_buffer_Array_V_1581_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd5),
    .ce0(line_buffer_Array_V_1581_6_ce0),
    .we0(line_buffer_Array_V_1581_6_we0),
    .d0(line_buffer_Array_V_0_6_q0),
    .q0(line_buffer_Array_V_1581_6_q0)
);

shift_line_buffer_array_ap_fixed_10u_config10_s_line_buffLf8 #(
    .DataWidth( 16 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
line_buffer_Array_V_0_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd5),
    .ce0(line_buffer_Array_V_0_7_ce0),
    .we0(line_buffer_Array_V_0_7_we0),
    .d0(kernel_window_87_V_write),
    .q0(line_buffer_Array_V_0_7_q0)
);

shift_line_buffer_array_ap_fixed_10u_config10_s_line_buffLf8 #(
    .DataWidth( 16 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
line_buffer_Array_V_1581_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd5),
    .ce0(line_buffer_Array_V_1581_7_ce0),
    .we0(line_buffer_Array_V_1581_7_we0),
    .d0(line_buffer_Array_V_0_7_q0),
    .q0(line_buffer_Array_V_1581_7_q0)
);

shift_line_buffer_array_ap_fixed_10u_config10_s_line_buffLf8 #(
    .DataWidth( 16 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
line_buffer_Array_V_0_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd5),
    .ce0(line_buffer_Array_V_0_8_ce0),
    .we0(line_buffer_Array_V_0_8_we0),
    .d0(kernel_window_88_V_write),
    .q0(line_buffer_Array_V_0_8_q0)
);

shift_line_buffer_array_ap_fixed_10u_config10_s_line_buffLf8 #(
    .DataWidth( 16 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
line_buffer_Array_V_1581_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd5),
    .ce0(line_buffer_Array_V_1581_8_ce0),
    .we0(line_buffer_Array_V_1581_8_we0),
    .d0(line_buffer_Array_V_0_8_q0),
    .q0(line_buffer_Array_V_1581_8_q0)
);

shift_line_buffer_array_ap_fixed_10u_config10_s_line_buffLf8 #(
    .DataWidth( 16 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
line_buffer_Array_V_0_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd5),
    .ce0(line_buffer_Array_V_0_9_ce0),
    .we0(line_buffer_Array_V_0_9_we0),
    .d0(kernel_window_89_V_write),
    .q0(line_buffer_Array_V_0_9_q0)
);

shift_line_buffer_array_ap_fixed_10u_config10_s_line_buffLf8 #(
    .DataWidth( 16 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
line_buffer_Array_V_1581_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd5),
    .ce0(line_buffer_Array_V_1581_9_ce0),
    .we0(line_buffer_Array_V_1581_9_we0),
    .d0(line_buffer_Array_V_0_9_q0),
    .q0(line_buffer_Array_V_1581_9_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_0_0_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_0_0_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_0_1_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_0_1_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_0_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_0_2_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_0_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_0_2_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_0_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_0_3_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_0_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_0_3_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_0_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_0_4_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_0_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_0_4_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_0_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_0_5_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_0_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_0_5_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_0_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_0_6_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_0_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_0_6_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_0_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_0_7_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_0_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_0_7_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_0_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_0_8_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_0_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_0_8_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_0_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_0_9_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_0_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_0_9_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_0_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_1581_0_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_1581_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_1581_0_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_1581_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_1581_1_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_1581_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_1581_1_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_1581_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_1581_2_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_1581_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_1581_2_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_1581_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_1581_3_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_1581_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_1581_3_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_1581_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_1581_4_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_1581_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_1581_4_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_1581_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_1581_5_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_1581_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_1581_5_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_1581_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_1581_6_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_1581_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_1581_6_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_1581_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_1581_7_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_1581_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_1581_7_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_1581_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_1581_8_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_1581_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_1581_8_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_1581_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_1581_9_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_1581_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_V_1581_9_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_1581_9_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_return_0 = kernel_window_10_V_read;

assign ap_return_1 = kernel_window_11_V_read;

assign ap_return_10 = kernel_window_40_V_read;

assign ap_return_11 = kernel_window_41_V_read;

assign ap_return_12 = kernel_window_42_V_read;

assign ap_return_13 = kernel_window_43_V_read;

assign ap_return_14 = kernel_window_44_V_read;

assign ap_return_15 = kernel_window_45_V_read;

assign ap_return_16 = kernel_window_46_V_read;

assign ap_return_17 = kernel_window_47_V_read;

assign ap_return_18 = kernel_window_48_V_read;

assign ap_return_19 = kernel_window_49_V_read;

assign ap_return_2 = kernel_window_12_V_read;

assign ap_return_20 = kernel_window_70_V_read;

assign ap_return_21 = kernel_window_71_V_read;

assign ap_return_22 = kernel_window_72_V_read;

assign ap_return_23 = kernel_window_73_V_read;

assign ap_return_24 = kernel_window_74_V_read;

assign ap_return_25 = kernel_window_75_V_read;

assign ap_return_26 = kernel_window_76_V_read;

assign ap_return_27 = kernel_window_77_V_read;

assign ap_return_28 = kernel_window_78_V_read;

assign ap_return_29 = kernel_window_79_V_read;

assign ap_return_3 = kernel_window_13_V_read;

assign ap_return_30 = kernel_window_20_V_read;

assign ap_return_31 = kernel_window_21_V_read;

assign ap_return_32 = kernel_window_22_V_read;

assign ap_return_33 = kernel_window_23_V_read;

assign ap_return_34 = kernel_window_24_V_read;

assign ap_return_35 = kernel_window_25_V_read;

assign ap_return_36 = kernel_window_26_V_read;

assign ap_return_37 = kernel_window_27_V_read;

assign ap_return_38 = kernel_window_28_V_read;

assign ap_return_39 = kernel_window_29_V_read;

assign ap_return_4 = kernel_window_14_V_read;

assign ap_return_40 = line_buffer_Array_V_1581_0_q0;

assign ap_return_41 = line_buffer_Array_V_1581_1_q0;

assign ap_return_42 = line_buffer_Array_V_1581_2_q0;

assign ap_return_43 = line_buffer_Array_V_1581_3_q0;

assign ap_return_44 = line_buffer_Array_V_1581_4_q0;

assign ap_return_45 = line_buffer_Array_V_1581_5_q0;

assign ap_return_46 = line_buffer_Array_V_1581_6_q0;

assign ap_return_47 = line_buffer_Array_V_1581_7_q0;

assign ap_return_48 = line_buffer_Array_V_1581_8_q0;

assign ap_return_49 = line_buffer_Array_V_1581_9_q0;

assign ap_return_5 = kernel_window_15_V_read;

assign ap_return_50 = kernel_window_50_V_read;

assign ap_return_51 = kernel_window_51_V_read;

assign ap_return_52 = kernel_window_52_V_read;

assign ap_return_53 = kernel_window_53_V_read;

assign ap_return_54 = kernel_window_54_V_read;

assign ap_return_55 = kernel_window_55_V_read;

assign ap_return_56 = kernel_window_56_V_read;

assign ap_return_57 = kernel_window_57_V_read;

assign ap_return_58 = kernel_window_58_V_read;

assign ap_return_59 = kernel_window_59_V_read;

assign ap_return_6 = kernel_window_16_V_read;

assign ap_return_60 = line_buffer_Array_V_0_0_q0;

assign ap_return_61 = line_buffer_Array_V_0_1_q0;

assign ap_return_62 = line_buffer_Array_V_0_2_q0;

assign ap_return_63 = line_buffer_Array_V_0_3_q0;

assign ap_return_64 = line_buffer_Array_V_0_4_q0;

assign ap_return_65 = line_buffer_Array_V_0_5_q0;

assign ap_return_66 = line_buffer_Array_V_0_6_q0;

assign ap_return_67 = line_buffer_Array_V_0_7_q0;

assign ap_return_68 = line_buffer_Array_V_0_8_q0;

assign ap_return_69 = line_buffer_Array_V_0_9_q0;

assign ap_return_7 = kernel_window_17_V_read;

assign ap_return_70 = kernel_window_80_V_read;

assign ap_return_71 = kernel_window_81_V_read;

assign ap_return_72 = kernel_window_82_V_read;

assign ap_return_73 = kernel_window_83_V_read;

assign ap_return_74 = kernel_window_84_V_read;

assign ap_return_75 = kernel_window_85_V_read;

assign ap_return_76 = kernel_window_86_V_read;

assign ap_return_77 = kernel_window_87_V_read;

assign ap_return_78 = kernel_window_88_V_read;

assign ap_return_79 = kernel_window_89_V_read;

assign ap_return_8 = kernel_window_18_V_read;

assign ap_return_80 = kernel_window_80_V_write;

assign ap_return_81 = kernel_window_81_V_write;

assign ap_return_82 = kernel_window_82_V_write;

assign ap_return_83 = kernel_window_83_V_write;

assign ap_return_84 = kernel_window_84_V_write;

assign ap_return_85 = kernel_window_85_V_write;

assign ap_return_86 = kernel_window_86_V_write;

assign ap_return_87 = kernel_window_87_V_write;

assign ap_return_88 = kernel_window_88_V_write;

assign ap_return_89 = kernel_window_89_V_write;

assign ap_return_9 = kernel_window_19_V_read;

endmodule //shift_line_buffer_array_ap_fixed_10u_config10_s
